name: Robot Code A-Z - Synchro Automatique

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Récupération du code source
        uses: actions/checkout@v4

      - name: 2. Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 3. Installation de Google Chrome (Requis pour Puppeteer)
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome

      - name: 4. Installation des dépendances
        run: npm ci

      - name: 5. Lancement du robot Code A-Z
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
        run: node scraper.js

      - name: 6. Sauvegarde et Push de matchs.json
        run: |
          git config --global user.name "Code A-Z Automation"
          git config --global user.email "bot@codeaz.com"
          git add matchs.json
          git commit -m "🔄 [Bot] Actualisation automatique des matchs" || exit 0
          git pull --rebase origin main  # <--- AJOUTE CETTE LIGNE
          git push