name: Robot Code AZ - Synchro Automatique

on:
  schedule:
    # ⚽ MODE COUPE DU MONDE : Toutes les 30 min entre 15h00 et 05h59 GMT (Heure Abidjan)
    - cron: '*/30 15-23,0-5 * * *'
    
    # 💤 MODE VEILLE : Toutes les 3 heures entre 06h00 et 14h59 GMT pendant le calme
    - cron: '0 6,9,12 * * *'
  workflow_dispatch: # Permet de lancer le robot manuellement en un clic sur GitHub pour tester

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Récupération du code source
        uses: actions/checkout@v3

      - name: 2. Installation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 3. Installation des dépendances
        run: npm install

      - name: 4. Lancement du robot Code A Z
        env:
          CRAWLBASE_TOKEN: ${{ secrets.CRAWLBASE_TOKEN }}
        run: node scraper.js

      - name: 5. Sauvegarde et Push de matchs.json
        run: |
          git config --global user.name "Robot Code A-Z"
          git config --global user.email "robot@codeaz.com"
          git add matchs.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Synchro Auto : Mise à jour des matchs" && git push)